name: Code workflows
on: [push]
jobs:
  lint-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tox with run-tox-gh-actions
        uses: ymyzk/run-tox-gh-actions@main
        with:
          tox-args:
            -e py38-lint


  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tox with run-tox-gh-actions
        uses: ymyzk/run-tox-gh-actions@main
